### PR TITLE
Update installer to official MSI framework

### LINKED ISSUE #45: Outdated installer linked in README
The link to download OnTopReplica In the project README points to an outdated repository. The release linked is version 3.5.1 from paulodeleo/OnTopReplica, which was last updated 2017-06-13. 

The installer should be updated so that it is current with this repository. I propose using [Microsoft's official installer solution](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects), which produces an MSI, instead of creating an installer with NSIS.

Suggestions and feedback are welcome.

TODO:
- [x] Fork repository
- [x] Build updated installer as an MSI
- [x] Test installer
- [x] Update README links
- [x] Submit PR
- [x] QA and code review
- [ ] Release as v3.6.0

### PR DESCRIPTION
**Pull request by andrewjmetzger**
Closes #45

### CODE REVIEW

**Comment by andrewjmetzger** [comment]
@blundercode Thanks! 

It's just the installer, although I think it's a good start. Someone more versed in C# than I should add support for automatic updates and change all of the OnTopReplica version strings, though.

**Comment by blundercode** [comment]
This repo is great one of my favorites I believe the person running it is overwhelmed though I really wish I knew any C# to assist running it. It's really cool your contributing, not many people do.

**Comment by LorenzCK** [comment]
Hey @andrewjmetzger,
thank you so much for the (much needed) pull request: I never found the time to look into how to generate an&nbsp;MSI installer. I had to make some minor changes and squashed the commits, so I'm closing this pull request here, but the changes have been pushed to the `feature/msi-installer` branch and I made sure you appear as the author of the commits.

There is one last thing missing in the MSI&nbsp;installer: the shortcut to the installed application needs the `System.AppUserModel.ID` property set to `LorenzCunoKlopfenstein.OnTopReplica.MainForm` in order to be pinned correctly on the Win&nbsp;7 Taskbar. However, as soon as this is done I'll merge your changes into master and release the MSI.

Thanks again! 🙏

**Comment by andrewjmetzger** [comment]
@LorenzCK Sorry to reopen this, didn't want to file a new PR until I had a solution. However, I cannot seem to set the property on the generated desktop shortcut in Visual Studio 2017.

**Comment by LorenzCK** [comment]
Yes, I was unable to find anything related to setting that property as well. I “fixed” it like I did in the original NSIS&nbsp;script: using an additional dedicated executable that is launched during the installation and sets the property on the shortcut. Bit of a hack, but it works in MSI as well as a “Custom Action”. 👍

**Comment by andrewjmetzger** [comment]
Excellent, thank you!

**Pull request closed without merging**
